[package]
publish = ["idle-editchain"]
name = "editchain-index"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
editchain-core = { registry = "idle-editchain", version = "0.1.4", path = "../editchain-core" }
editchain-store = { registry = "idle-editchain", version = "0.1.4", path = "../editchain-store" }
editchain-index-pages = { registry = "idle-editchain", version = "0.1.4", path = "../editchain-index-pages" }
serde = { workspace = true, features = ["rc"] }

[dev-dependencies]
postcard.workspace = true
blake3 = "1"
tempfile = "3"
