[package]
name = "editchain-project"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
editchain-core = { path = "../editchain-core" }
regex.workspace = true