[package]
publish = ["idle-editchain"]
name = "editchain-store"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
editchain-index-pages = { registry = "idle-editchain", version = "0.1.1", path = "../editchain-index-pages" }
postcard.workspace = true
crc = "3"
blake3 = "1"
editchain-core = { registry = "idle-editchain", version = "0.1.1", path = "../editchain-core" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
proptest = "1"
tempfile = "3"
