[package]
name = "editchain-vscode-service"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
serde_json = "1"
serde = { workspace = true }
blake3 = "1"
editchain-core = { path = "../editchain-core" }
editchain-codec = { path = "../editchain-codec" }
editchain-git = { path = "../editchain-git" }
editchain-project = { path = "../editchain-project" }
editchain-protocol = { path = "../editchain-protocol" }
editchain-index = { path = "../editchain-index" }

[dev-dependencies]
tempfile = "3"
editchain-import = { path = "../editchain-import" }
